// <auto-generated />
using System;
using GestaoEscolar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestaoEscolar.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181112221033_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestaoEscolar.Models.Aluno", b =>
                {
                    b.Property<decimal>("id");

                    b.Property<string>("celular");

                    b.Property<string>("codigo");

                    b.Property<DateTime>("dataAniversario");

                    b.Property<string>("localNascimento");

                    b.Property<string>("morada");

                    b.Property<string>("nome");

                    b.Property<bool>("sexo");

                    b.Property<string>("telefone");

                    b.HasKey("id");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("GestaoEscolar.Models.Aluno_Efectividade", b =>
                {
                    b.Property<decimal>("Id");

                    b.Property<decimal?>("Aluno_Id");

                    b.Property<decimal?>("Alunoid");

                    b.Property<decimal?>("Ano_Id");

                    b.Property<int?>("Anoid");

                    b.Property<decimal?>("Classe_Id");

                    b.Property<decimal?>("Dia");

                    b.Property<int?>("Mes");

                    b.Property<string>("Objservacao");

                    b.Property<int?>("Presenca");

                    b.HasKey("Id");

                    b.HasIndex("Alunoid");

                    b.HasIndex("Anoid");

                    b.ToTable("Aluno_Efectividade");
                });

            modelBuilder.Entity("GestaoEscolar.Models.AlunoAnoLectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Alunoid");

                    b.Property<decimal?>("AnoLectivoID");

                    b.Property<decimal>("Id_Aluno");

                    b.Property<decimal>("Id_AnoLectivo");

                    b.Property<decimal?>("Id_Turma");

                    b.Property<int?>("Turmasid");

                    b.HasKey("Id");

                    b.HasIndex("Alunoid");

                    b.HasIndex("AnoLectivoID");

                    b.HasIndex("Turmasid");

                    b.ToTable("AlunoAnoLectivo");
                });

            modelBuilder.Entity("GestaoEscolar.Models.AnoLectivo", b =>
                {
                    b.Property<decimal>("ID");

                    b.Property<decimal?>("Ano_Id");

                    b.Property<int?>("Anosid");

                    b.Property<decimal?>("Classe_Id");

                    b.Property<int?>("Classeid");

                    b.HasKey("ID");

                    b.HasIndex("Anosid");

                    b.HasIndex("Classeid");

                    b.ToTable("AnoLectivo");
                });

            modelBuilder.Entity("GestaoEscolar.Models.Anos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ESTADO");

                    b.Property<DateTime?>("FIM");

                    b.Property<DateTime?>("INICIO");

                    b.Property<decimal?>("ano");

                    b.HasKey("id");

                    b.ToTable("Anos");
                });

            modelBuilder.Entity("GestaoEscolar.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("GestaoEscolar.Models.Classe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("desc")
                        .HasMaxLength(20);

                    b.Property<string>("nivelCode")
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.HasIndex("nivelCode");

                    b.ToTable("Classe");
                });

            modelBuilder.Entity("GestaoEscolar.Models.Disciplina", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("classe_id");

                    b.Property<string>("desc")
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.HasIndex("classe_id");

                    b.ToTable("Disciplina");
                });

            modelBuilder.Entity("GestaoEscolar.Models.Nivel", b =>
                {
                    b.Property<string>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20);

                    b.Property<string>("desc")
                        .HasMaxLength(20);

                    b.HasKey("codigo");

                    b.ToTable("Nivel");
                });

            modelBuilder.Entity("GestaoEscolar.Models.TabelaHorarios", b =>
                {
                    b.Property<decimal>("ID");

                    b.Property<string>("Entrada");

                    b.Property<string>("Saida");

                    b.HasKey("ID");

                    b.ToTable("TabelaHorarios");
                });

            modelBuilder.Entity("GestaoEscolar.Models.Turmas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("AnoLectivoID");

                    b.Property<int?>("AnoLectivoId");

                    b.Property<int?>("HorarioId");

                    b.Property<decimal?>("TabelaHorariosID");

                    b.Property<int>("classeId");

                    b.Property<string>("desc")
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.HasIndex("AnoLectivoID");

                    b.HasIndex("TabelaHorariosID");

                    b.HasIndex("classeId");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("GestaoEscolar.Models.Aluno_Efectividade", b =>
                {
                    b.HasOne("GestaoEscolar.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("Alunoid");

                    b.HasOne("GestaoEscolar.Models.Anos", "Ano")
                        .WithMany("Aluno_Efectividade")
                        .HasForeignKey("Anoid");
                });

            modelBuilder.Entity("GestaoEscolar.Models.AlunoAnoLectivo", b =>
                {
                    b.HasOne("GestaoEscolar.Models.Aluno", "Aluno")
                        .WithMany("AlunoAnoLectivo")
                        .HasForeignKey("Alunoid");

                    b.HasOne("GestaoEscolar.Models.AnoLectivo", "AnoLectivo")
                        .WithMany("AlunoAnoLectivo")
                        .HasForeignKey("AnoLectivoID");

                    b.HasOne("GestaoEscolar.Models.Turmas", "Turmas")
                        .WithMany("AlunoAnoLectivo")
                        .HasForeignKey("Turmasid");
                });

            modelBuilder.Entity("GestaoEscolar.Models.AnoLectivo", b =>
                {
                    b.HasOne("GestaoEscolar.Models.Anos", "Anos")
                        .WithMany("AnoLectivo")
                        .HasForeignKey("Anosid");

                    b.HasOne("GestaoEscolar.Models.Classe", "Classe")
                        .WithMany("AnoLectivo")
                        .HasForeignKey("Classeid");
                });

            modelBuilder.Entity("GestaoEscolar.Models.Classe", b =>
                {
                    b.HasOne("GestaoEscolar.Models.Nivel", "Nivel")
                        .WithMany()
                        .HasForeignKey("nivelCode");
                });

            modelBuilder.Entity("GestaoEscolar.Models.Disciplina", b =>
                {
                    b.HasOne("GestaoEscolar.Models.Classe", "classe")
                        .WithMany("Disciplinas")
                        .HasForeignKey("classe_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GestaoEscolar.Models.Turmas", b =>
                {
                    b.HasOne("GestaoEscolar.Models.AnoLectivo", "AnoLectivo")
                        .WithMany("Turmas")
                        .HasForeignKey("AnoLectivoID");

                    b.HasOne("GestaoEscolar.Models.TabelaHorarios", "TabelaHorarios")
                        .WithMany("Turmas")
                        .HasForeignKey("TabelaHorariosID");

                    b.HasOne("GestaoEscolar.Models.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("classeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GestaoEscolar.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GestaoEscolar.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GestaoEscolar.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GestaoEscolar.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
